---
title: "The dangers of teenage driving"
subtitle: "risk factors related to teenage driving"
author: 
  - Ariel Xu
thanks: "Code and data are available at: https://github.com/Ariel-Q/304-Final-paper.git"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: " This paper replicates the 2021 article ‘Teenage Driving, Mortality, and Risky Behaviors”[@Huh2021Teenage]’, which explores possible correlations between adolescent mortality and adolescent driving and suicidal behavior. The goal of our replication is to improve on the paper and seek more possible relationships with adolescent mortality. Finally, we found more evidence to support the original results from different angles, and they were consistent"
output: pdf_document
toc: True
bibliography: references.bib
---

```{r setup, include=FALSE}
library(haven)
library(tidyverse)
library(RStata)
library(ggplot2)
library(gridExtra)
library(here)
library(readr)
library(knitr)
```

\newpage
# Introduction

With the development of technology, the popularity of cars is gradually increasing in every country, and the behavior of teenagers driving cars is becoming more and more common. However, studies show that motor vehicle accidents caused by teen driving are one of the leading causes of death among teenagers in the United States. However, the risk factors behind teen driving accidents have not been further discussed. Some studies have shown that dangerous driving among teenagers is associated with drug and alcohol abuse.

This paper replicates the "Teenage Driving, Mortality, and Risky Behaviors”[@Huh2021Teenage], focusing on the impact of various factors on teen driving accidents and death rates, such as driver's license holding rate, gender, age, drunkenness and suicide. My goal is to explore the data further to explore possible hidden associations between multiple factors. We hypothesized that there was a correlation between driver's license ownership and adolescent mortality, and that drug use and suicide were also associated with adolescent deaths from driving accidents

The rest of this paper is organized as follows: In the data section, we explore the correlation between age and driving and death rate, and study the influence of driving qualification on driving and death rate of adolescents. In the results section, we show the impact of selected variables on adolescent mortality and how each factor changes over time. In the discussion section, we comment on this article and discuss possible biases in the research. Finally, we propose potential factors not included by the authors to illustrate future directions of this research.

# Data

The research uses `R` language[@citeR] as its foundation, where we have used packages such as `tidyverse`[@tidyverse], `haven`[@haven], `here`[@here], `readr`[@readr] to prepare data for this project.Where we then used `Kable`[@kableExtra] to generate table and `ggplot`[@ggplot2] to generate plots.

## Orginal paper


## Data Source


## Data analysis

## Descriptive analysis

# Results


# Discussion

\newpage

# Appendix


\newpage

# References



